language: java
matrix:
  include:
    # XXX: JDKs `openjdk9` and `openjdk10` are currently not targeted because
    # in those environments attempts to download
    # `junit:junit:jar:4.13-SNAPSHOT` from the Sonatype Nexus Snapshots
    # repository trigger the issue described at
    # https://github.com/travis-ci/travis-ci/issues/9368#issuecomment-405035447.
    - jdk: oraclejdk8
      # This is the primary target platform. In this build we track test
      # coverage and perform a SonarQube analysis.
      script:
        - ./mvnw install
        # XXX: Enable Coveralls and SonarCloud once we "go public".
        # ./mvnw jacoco:prepare-agent surefire:test jacoco:report coveralls:report sonar:sonar
        - ./mvnw jacoco:prepare-agent surefire:test jacoco:report
    - jdk: openjdk8
      script: ./mvnw install
    - jdk: oraclejdk9
      script: ./mvnw install
    - jdk: oraclejdk10
      script: ./mvnw install
    - jdk: openjdk-ea
      # XXX: When running the tests under JDK 11 they fail because expected
      # errors are not reported. Investigate.
      script: ./mvnw install -DskipTests
addons:
  sonarcloud:
    organization: picnic-technologies
    token: "${SONARCLOUD_TOKEN}"
install: mvn io.takari:maven:wrapper
before_cache:
  # Don't cache the artifacts we just generated, for multiple reasons: (1) we
  # shouldn't need them next time around and (2) if we do, that indicates a
  # dependency issue which might otherwise go unnoticed until next time we bump
  # the project's version (i.e., when tagging).
  - find "${HOME}/.m2/repository" -depth -name '*-SNAPSHOT' -exec rm -r '{}' \;
cache:
  directories:
    # The local Maven repository in which third party dependencies are stored.
    - ${HOME}/.m2/repository
    # The Takari Maven Wrapper's storage for downloaded Maven distributions.
    - ${HOME}/.m2/wrapper
    # The SonarQube analysis cache.
    - ${HOME}/.sonar/cache
